api:
  dashboard: true
  debug: true
# log:
#   level: debug
#   filePath: /etc/traefik/traefik.log
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  # file:
  #   filename: /etc/traefik/config.yml
certificatesResolvers:
  porkbun:
    acme:
      email: alec.minch@gmail.com
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: porkbun
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        #delayBeforeCheck: 60s # uncomment along with disablePropagationCheck if needed to ensure the TXT record is ready before verification is attempted
        # use public DNS servers for the check to avoid having to wait for the records to propagate to your router
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
